_default:
	@just --list --unsorted --list-heading '' --list-prefix '—— '

ghdl_flags := "--std=08"

# order matters
sources := "\
types.vhd \
alu.vhd \
rom.vhd \
accumulator.vhd \
control_unit.vhd \
regfile.vhd \
cpu.vhd \
"

tb_sources := "\
alu_tb.vhd \
rom_tb.vhd \
cpu_tb.vhd \
"

analyze *args:
	ghdl analyze {{ghdl_flags}} {{sources}} {{tb_sources}} {{args}}

run entity *args: analyze
	ghdl elab-run {{ghdl_flags}} {{entity}} {{args}} --wave={{entity}}.ghw

view entity: (run entity)
	gtkwave {{entity}}.ghw --script {{entity}}.tcl

synthesize entity *args:
	yosys -p 'ghdl --latches {{ghdl_flags}} {{sources}}  -e {{entity}}; opt; show' {{args}}

clean:
	@rm -vf work-obj08.cf
	@rm -vf *.vcf *.ghw
	@rm -vf *.netlist.svg *.netlist.json
